# Generated by Django 4.2.9 on 2026-01-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_universe', models.JSONField(help_text='List of symbols to evaluate')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_timeframe', models.CharField(default='5m', max_length=5)),
                ('window_hours', models.IntegerField(default=4)),
                ('shift_hours', models.IntegerField(default=2)),
                ('fee_bps', models.IntegerField(default=10, help_text='Fee in basis points (10 = 0.10%)')),
                ('slippage_bps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('module_path', models.CharField(help_text='e.g. core_engine.strategies.macd_rsi_confluence:MACDRSIStrategy', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Strategy hyperparameters as JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_return_pct', models.FloatField(default=0.0)),
                ('median_return_pct', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(default=0.0)),
                ('total_return_pct', models.FloatField(default=0.0)),
                ('backtest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.backtestrun')),
            ],
            options={
                'verbose_name_plural': 'Strategy performances',
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='trading_can_symbol_bb7352_idx'), models.Index(fields=['timestamp'], name='trading_can_timesta_ed9687_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy'),
        ),
        migrations.CreateModel(
            name='TradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('direction', models.CharField(default='LONG', max_length=10)),
                ('return_pct', models.FloatField(help_text='Return % after fees/slippage')),
                ('max_drawdown', models.FloatField(help_text='Max drawdown during holding period')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional: feature snapshots, ranks, etc.')),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.backtestrun')),
            ],
            options={
                'ordering': ['entry_time'],
                'indexes': [models.Index(fields=['backtest', 'entry_time'], name='trading_tra_backtes_132f3d_idx')],
            },
        ),
    ]
