# Generated by Django 4.2.9 on 2026-01-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='max_hold_override',
            field=models.FloatField(blank=True, help_text="Optional: Override strategy's default max hold time (hours)", null=True),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='base_timeframe',
            field=models.CharField(default='5m', help_text='Auto-populated from strategy.preferred_timeframe', max_length=5),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='shift_hours',
            field=models.IntegerField(default=2, help_text='Auto-populated from strategy.evaluation_interval_hours'),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='window_hours',
            field=models.IntegerField(default=4, help_text='Auto-populated from strategy.max_hold_hours'),
        ),
    ]
