# Generated by Django 4.2.9 on 2026-01-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_backtestrun_max_hold_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='shift_hours',
            field=models.FloatField(default=2, help_text='Auto-populated from strategy.evaluation_interval_hours'),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='window_hours',
            field=models.FloatField(default=4, help_text='Auto-populated from strategy.max_hold_hours'),
        ),
    ]
