# Generated by Django 4.2.27 on 2026-01-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_backtestrun_shift_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alpha_score', models.FloatField(help_text='Alpha score from -1 (strong sell) to +1 (strong buy)')),
                ('confidence', models.FloatField(help_text='Confidence level from 0 to 1')),
                ('horizon_days', models.IntegerField(help_text='Prediction timeframe in days')),
                ('volatility_adjusted', models.BooleanField(default=False, help_text='Whether alpha_score accounts for volatility')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Strategy-specific details (indicators, thresholds, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['strategy_name', 'symbol', 'timestamp'], name='trading_str_strateg_977f44_idx'), models.Index(fields=['timestamp', 'symbol'], name='trading_str_timesta_ed8142_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('combination_method', models.CharField(help_text='Signal combination method used', max_length=50)),
                ('allocation_method', models.CharField(help_text='Capital allocation method used', max_length=50)),
                ('total_capital', models.FloatField(help_text='Total capital allocated')),
                ('allocations', models.JSONField(help_text='Dict mapping symbol -> allocation amount')),
                ('combined_alphas', models.JSONField(blank=True, default=dict, help_text='Combined alpha scores for each symbol')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Constraints used (max_position_pct, etc.)')),
                ('num_positions', models.IntegerField(default=0)),
                ('num_strategies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='trading_por_timesta_599e87_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(db_index=True)),
                ('lookback_days', models.IntegerField(help_text='Number of days used for evaluation')),
                ('total_return', models.FloatField(default=0.0)),
                ('cagr', models.FloatField(default=0.0, help_text='Compound Annual Growth Rate')),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('sortino_ratio', models.FloatField(blank=True, default=0.0, null=True)),
                ('calmar_ratio', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_drawdown', models.FloatField(default=0.0)),
                ('volatility', models.FloatField(default=0.0)),
                ('var_95', models.FloatField(blank=True, default=0.0, help_text='Value at Risk (95% confidence)', null=True)),
                ('win_rate', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_win_loss_ratio', models.FloatField(blank=True, default=0.0, null=True)),
                ('turnover', models.FloatField(blank=True, default=0.0, help_text='Portfolio turnover rate', null=True)),
                ('avg_holding_period', models.FloatField(blank=True, default=0.0, help_text='Average holding period in hours', null=True)),
                ('ic_mean', models.FloatField(blank=True, default=0.0, help_text='Mean Information Coefficient (alpha vs actual correlation)', null=True)),
                ('alpha_decay', models.FloatField(blank=True, default=0.0, help_text='How quickly predictive power fades', null=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict, help_text='Complete metrics dictionary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'indexes': [models.Index(fields=['strategy', 'evaluation_date'], name='trading_str_strateg_40fd54_idx')],
                'unique_together': {('strategy', 'evaluation_date', 'lookback_days')},
            },
        ),
    ]
