"""Data structures and schemas."""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class OHLCV:
    """Single candlestick data point."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class SymbolInfo:
    """Symbol metadata."""
    symbol: str
    base_asset: str
    quote_asset: str
    min_quantity: Optional[float] = None
    max_quantity: Optional[float] = None
    tick_size: Optional[float] = None


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    timestamp: datetime
    symbol: str
    direction: str  # "LONG", "SHORT", "FLAT"
    confidence: float = 1.0
    metadata: dict = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}
